---
title: "Gisler_Pinelli_Analysis"
author: "Marius Gisler"
date: "8 9 2020"
output: html_document
---
```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)

```

```{r setup, include=FALSE}
###Data Loading
df <- read.csv('https://raw.githubusercontent.com/gpluzern/r_bootcamp/master/2020_Results.csv?token=ALJMYDAKLZHYUJCCN4RW3N27LDBJY', header =TRUE, sep=";")
df <- data.frame(df)

df_1 <- read.csv('https://github.com/gpluzern/r_bootcamp/blob/master/Year_Downhill_Results.xlsx', header = TRUE, sep = ":")
```

```{r setup, include=FALSE}
###Data Inspection and Cleaning

#head(df)
colnames(df)
#View(df)
#str(df)
#summary(df)


### Rename NSA.Code to Nation
names(df)[names(df) == "NSA.Code"] <- "Nation"
names(df)[names(df) == "ï..Rank" ] <- "Rank"
names(df)[names(df) == "Year.of.Birth" ] <- "Year_of_birth"
names(df)[names(df) == "Distance..m." ] <- "Distance_in_meters"
names(df)[names(df) == "Race.Points" ] <- "Race_points"
names(df)[names(df) == "Race.Day" ] <- "Race_day"
names(df)[names(df) == "FIS.Code" ] <- "FIS_code"
names(df)[names(df) == "Last.Name" ] <- "Last_name"
names(df)[names(df) == "First.Name" ] <- "First_name"

### Add Column Number_of_Participations
occurence <- table(df$FIS_code)
occurence <- as.data.frame(occurence)
names(occurence)[names(occurence) == "Var1"] <- "FIS_code"
names(occurence)[names(occurence) == "Freq"] <- "Number_of_participations"
df <- merge(df,occurence,by="FIS_code")


### Change charachter format to date format for column Race_day
df$Race_day <- as.factor(df$Race_day)
df$Race_day <- as.Date(df$Race_day, "%d.%m.%Y")
#head(df$Race_day)
#str(df$Race_day)

### Change chr format to time format for column Time
head(df$Time)
str(df$Time)
# View(df$Time)
# 
# df['newtime'] <- strptime(df$Time, "%M:%OS")
# df$newtime # prints without fractional seconds
# op <- options(digits.secs=3)



### Change num format to time format for column Difference
#head(df$Difference)

# str(df$Difference)
# 
# test <- strftime(df$Difference, format = "%OS")
# 
# ?strptime


###Add Age of Rider at Race
df$year_of_race <- format(as.Date(df$Race_day, format="%d.%m.%Y"),"%Y")
df$year_of_race <- as.integer(df$year_of_race)
df$Age_of_rider <- df$year_of_race - df$Year_of_birth
#colnames(df)

View(df)

```


```{r setup, include=FALSE}
### All riders
### Birthyears
hist(df$Year_of_birth)

### Ski Brands
ggplot(data = df, aes(x=Ski)) +
  geom_bar()

### Nationalites
ggplot(data = df, aes(x=Nation)) +
  geom_bar()

### Age of Riders
ggplot(data = df, aes(x=Age_of_rider)) +
  geom_bar()

### Number of Riders
df_podium <- filter(df, df$Rank <4)

ggplot(data = df_podium, aes(x=Last_name)) +
  geom_bar()

```

```{r setup, include=FALSE}
### Winners
df_winner <- filter(df, df$Rank == 1)

### Ski Brands
ggplot(data = df_winner, aes(x=Ski)) +
  geom_bar()

### Nationalites
ggplot(data = df_winner, aes(x=Nation)) +
  geom_bar()

### Age of Riders
ggplot(data = df_winner, aes(x=Age_of_rider)) +
  geom_bar()

### Riders
ggplot(data = df_winner, aes(x=Last_name)) +
  geom_bar()

View(df_winner)

df_second <- filter(df, df$Rank == 2)
View(df_second)

```


```{r setup, include=FALSE}
### Podium
df_podium <- filter(df, df$Rank <4)

### Ski Brands
ggplot(data = df_podium, aes(x=Ski)) +
  geom_bar()

### Nationalites
ggplot(data = df_podium, aes(x=Nation)) +
  geom_bar()

### Age of Riders
ggplot(data = df_podium, aes(x=Age_of_rider)) +
  geom_bar()

### Riders
ggplot(data = df_podium, aes(x=Last_name)) +
  geom_bar()

#df_participations <- filter(df, df$FIS_code <4)


View(df)


#assign occurence values to df by FIS Code



```
